### ISSUE TITLE
Unable to use patch operation after adding `apps.clusternet.io/skip-validating` for workload

### ISSUE THREAD

**Issue by silenceper** [clusternet/clusternet#468]
#### What happened:
```
kubectl clusternet edit deploy demo
error: deployments.apps "demo" could not be found on the server
The edits you made on deleted resources have been saved to "/tmp/kubectl-clusternet-edit-4205601414.yaml"
```

#### Environment:
- Clusternet version:
    - Clusternet-agent version (user `clusternet-agent --version=json`):
    - Clusternet-hub version (user `clusternet-hub --version=json`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dixudx** [comment]
> The edits you made on deleted resources have been saved to "/tmp/kubectl-clusternet-edit-4205601414.yaml"

The error is clear that you are patching on a deleted resource.

**Comment by silenceper** [comment]
No, this resource is not deleted, as long as Annotation `apps.clusternet.io/skip-validating` is added, the patch action will report this error.

**Comment by dixudx** [comment]
@silenceper I did not reproduce your issue.

```bash
$ kubectl clusternet edit ns abc -v 7
I0901 14:15:19.997323   55188 loader.go:372] Config loaded from file:  /root/.kube/config
I0901 14:15:20.017590   55188 round_trippers.go:463] GET https://10.0.3.38:6443/api/v1/namespaces/abc
I0901 14:15:20.017608   55188 round_trippers.go:469] Request Headers:
I0901 14:15:20.017616   55188 round_trippers.go:473]     Accept: application/json
I0901 14:15:20.017784   55188 round_trippers.go:473]     User-Agent: kubectl-clusternet/v0.0.0 (linux/amd64) kubernetes/$Format
I0901 14:15:20.054879   55188 round_trippers.go:574] Response Status: 200 OK in 37 milliseconds
I0901 14:15:20.055392   55188 editor.go:127] Opening file with editor [vi /tmp/kubectl-clusternet-edit-4176005555.yaml]
I0901 14:15:27.508297   55188 editoptions.go:297] User edited:
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    apps.clusternet.io/skip-validating: "true"
  creationTimestamp: "2022-09-01T06:13:25Z"
  generation: 3
  labels:
    a: c
    clusternet.io/created-by: clusternet-hub
    kubernetes.io/metadata.name: abc
  name: abc
  resourceVersion: "27191"
  uid: 373b9dca-cee5-4a40-bad5-feceb70f382e
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
I0901 14:15:27.508409   55188 round_trippers.go:463] GET https://10.0.3.38:6443/openapi/v2?timeout=32s
I0901 14:15:27.508421   55188 round_trippers.go:469] Request Headers:
I0901 14:15:27.508430   55188 round_trippers.go:473]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0901 14:15:27.508436   55188 round_trippers.go:473]     User-Agent: kubectl-clusternet/v0.0.0 (linux/amd64) kubernetes/$Format
I0901 14:15:27.536572   55188 round_trippers.go:574] Response Status: 200 OK in 28 milliseconds
I0901 14:15:27.607865   55188 round_trippers.go:463] PATCH https://10.0.3.38:6443/api/v1/namespaces/abc?fieldManager=kubectl-edit
I0901 14:15:27.607896   55188 round_trippers.go:469] Request Headers:
I0901 14:15:27.607905   55188 round_trippers.go:473]     User-Agent: kubectl-clusternet/v0.0.0 (linux/amd64) kubernetes/$Format
I0901 14:15:27.607914   55188 round_trippers.go:473]     Accept: application/json
I0901 14:15:27.607925   55188 round_trippers.go:473]     Content-Type: application/merge-patch+json
I0901 14:15:27.620271   55188 round_trippers.go:574] Response Status: 200 OK in 12 milliseconds
namespace/abc edited
```

**Comment by silenceper** [comment]
The clusternet version I am using is v1.10 version:
```
# kubectl clusternet apply -f test-deploy.yaml 
deployment.apps/my-nginx created
# kubectl clusternet get deploy -n foo -o yaml
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      apps.clusternet.io/skip-validating: "true"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"apps.clusternet.io/skip-validating":"true"},"labels":{"clusternet-app":"multi-cluster-nginx"},"name":"my-nginx","namespace":"foo"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2022-09-01T06:39:34Z"
    finalizers:
    - apps.clusternet.io/finalizer
    - apps.clusternet.io/feed-protection
    generation: 1
    labels:
      clusternet-app: multi-cluster-nginx
      clusternet.io/created-by: clusternet-hub
    name: my-nginx
    namespace: foo
    resourceVersion: "122696426"
    uid: 916fbe76-5ed3-4581-abdf-f4e917ee61c6
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - image: nginx:1.14.2
          name: nginx
          ports:
          - containerPort: 80
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
# kubectl clusternet edit deploy -n foo  my-nginx -v=7
I0901 14:40:06.912152   24388 loader.go:372] Config loaded from file:  /root/.kube/config
I0901 14:40:06.921022   24388 round_trippers.go:432] GET https://xxxxxxxxxxx:60002/apis/apps/v1/namespaces/foo/deployments/my-nginx
I0901 14:40:06.921044   24388 round_trippers.go:438] Request Headers:
I0901 14:40:06.921059   24388 round_trippers.go:442]     Accept: application/json
I0901 14:40:06.921068   24388 round_trippers.go:442]     User-Agent: kubectl-clusternet/v0.0.0 (linux/amd64) kubernetes/$Format
I0901 14:40:06.921077   24388 round_trippers.go:442]     Authorization: Bearer <masked>
I0901 14:40:06.929179   24388 round_trippers.go:457] Response Status: 200 OK in 8 milliseconds
I0901 14:40:06.929692   24388 editor.go:128] Opening file with editor [vi /tmp/kubectl-clusternet-edit-2s1im.yaml]
I0901 14:40:15.358868   24388 editoptions.go:297] User edited:
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    apps.clusternet.io/skip-validating: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"apps.clusternet.io/skip-validating":"true"},"labels":{"clusternet-app":"multi-cluster-nginx"},"name":"my-nginx","namespace":"foo"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2022-09-01T06:39:34Z"
  finalizers:
  - apps.clusternet.io/finalizer
  - apps.clusternet.io/feed-protection
  generation: 1
  labels:
    clusternet-app: multi-cluster-nginx
    clusternet.io/created-by: clusternet-hub
  name: my-nginx
  namespace: foo
  resourceVersion: "122696426"
  uid: 916fbe76-5ed3-4581-abdf-f4e917ee61c6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
I0901 14:40:15.359384   24388 round_trippers.go:432] GET https://xxxxxxxxxxx:60002/openapi/v2?timeout=32s
I0901 14:40:15.359401   24388 round_trippers.go:438] Request Headers:
I0901 14:40:15.359410   24388 round_trippers.go:442]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0901 14:40:15.359419   24388 round_trippers.go:442]     User-Agent: kubectl-clusternet/v0.0.0 (linux/amd64) kubernetes/$Format
I0901 14:40:15.359429   24388 round_trippers.go:442]     Authorization: Bearer <masked>
I0901 14:40:15.371221   24388 round_trippers.go:457] Response Status: 200 OK in 11 milliseconds
I0901 14:40:15.557417   24388 round_trippers.go:432] PATCH https://xxxxxxxxxxx:60002/apis/apps/v1/namespaces/foo/deployments/my-nginx?fieldManager=kubectl-edit
I0901 14:40:15.557437   24388 round_trippers.go:438] Request Headers:
I0901 14:40:15.557448   24388 round_trippers.go:442]     User-Agent: kubectl-clusternet/v0.0.0 (linux/amd64) kubernetes/$Format
I0901 14:40:15.557459   24388 round_trippers.go:442]     Accept: application/json
I0901 14:40:15.557467   24388 round_trippers.go:442]     Content-Type: application/merge-patch+json
I0901 14:40:15.557477   24388 round_trippers.go:442]     Authorization: Bearer <masked>
I0901 14:40:15.563710   24388 round_trippers.go:457] Response Status: 404 Not Found in 6 milliseconds
error: deployments.apps "my-nginx" could not be found on the server
The edits you made on deleted resources have been saved to "/tmp/kubectl-clusternet-edit-2s1im.yaml"
F0901 14:40:15.563932   24388 helpers.go:115] 
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000010001, 0xc00079a000, 0x2f, 0xb4)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xb8
k8s.io/klog/v2.(*loggingT).output(0x372f820, 0xc000000003, 0x0, 0x0, 0xc0003fe070, 0x329d0a7, 0xa, 0x73, 0xc4a300)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x1a3
k8s.io/klog/v2.(*loggingT).printDepth(0x372f820, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0xc00544a5a0, 0x1, 0x1)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x16f
k8s.io/klog/v2.FatalDepth(...)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1495
k8s.io/kubectl/pkg/cmd/util.fatal(0x0, 0x0, 0x1)
        /root/go/pkg/mod/github.com/clusternet/kubectl@v0.21.3-0.20210908125438-a108a1408243/pkg/cmd/util/helpers.go:93 +0x263
k8s.io/kubectl/pkg/cmd/util.checkErr(0x25de680, 0xc000711200, 0x2442208)
        /root/go/pkg/mod/github.com/clusternet/kubectl@v0.21.3-0.20210908125438-a108a1408243/pkg/cmd/util/helpers.go:144 +0xb80
k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /root/go/pkg/mod/github.com/clusternet/kubectl@v0.21.3-0.20210908125438-a108a1408243/pkg/cmd/util/helpers.go:115
k8s.io/kubectl/pkg/cmd/edit.NewCmdEdit.func1(0xc00041f180, 0xc000113c20, 0x2, 0x5)
        /root/go/pkg/mod/github.com/clusternet/kubectl@v0.21.3-0.20210908125438-a108a1408243/pkg/cmd/edit/edit.go:81 +0xc3
github.com/spf13/cobra.(*Command).execute(0xc00041f180, 0xc000113bd0, 0x5, 0x5, 0xc00041f180, 0xc000113bd0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000404000, 0xc000010010, 0x25e0340, 0xc000010018)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /data/remote-vscode/test/kubectl-clusternet/cmd/kubectl-clusternet.go:43 +0x1a6

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x372f820)
        /root/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x8b
created by k8s.io/klog/v2.init.0
        /root/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xdd

goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x7fa64a0d6e30, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0009c0b18, 0x72, 0xa00, 0xa77, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0009c0b00, 0xc0001caa80, 0xa77, 0xa77, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0009c0b00, 0xc0001caa80, 0xa77, 0xa77, 0x203000, 0xf0eff0, 0xc00072e138)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000360010, 0xc0001caa80, 0xa77, 0xa77, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000cbe120, 0xc0001caa80, 0xa77, 0xa77, 0x400, 0x7fa64ca7df00, 0xc00065f9a8)
        /usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc00072e258, 0x25de500, 0xc000cbe120, 0xc47a65, 0x215f120, 0x22fa240)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00072e000, 0x25e0060, 0xc000360010, 0x5, 0xc000360010, 0x8)
        /usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc00072e000, 0x0, 0x0, 0xc00065fd18)
        /usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc00072e000, 0xc0001e1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
bufio.(*Reader).Read(0xc0000a9d40, 0xc000280118, 0x9, 0x9, 0xc00065fd18, 0x2442e00, 0x115a575)
        /usr/local/go/src/bufio/bufio.go:226 +0x24f
io.ReadAtLeast(0x25de340, 0xc0000a9d40, 0xc000280118, 0x9, 0x9, 0x9, 0xc00007c060, 0x0, 0x25de680)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc000280118, 0x9, 0x9, 0x25de340, 0xc0000a9d40, 0x0, 0xc000000000, 0xc906f2, 0xc00052c008)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/frame.go:237 +0x87
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0002800e0, 0xc000cca120, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00065ffa8, 0x0, 0x0)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/transport.go:1819 +0xd8
golang.org/x/net/http2.(*ClientConn).readLoop(0xc000836300)
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/transport.go:1741 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
        /root/go/pkg/mod/golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/transport.go:705 +0x6a6

goroutine 247 [syscall]:
os/signal.signal_recv(0x2)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /usr/local/go/src/os/signal/signal.go:127 +0x44
```
